services:
  app:
    build:
      context: ../
      dockerfile: infra/Dockerfile
      target: dev
    container_name: logi-app-dev
    volumes:
      - type: bind
        source: ../
        target: /app/
    networks:
      - logi-network
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - logi-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - logi-network
  rabbitmq:
    image: rabbitmq:4.1-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - logi-network


volumes:
  pgdata:

networks:
  logi-network:
