ALTER TABLE sender
DROP COLUMN is_verified;

ALTER TABLE sender
DROP COLUMN is_active;

ALTER TABLE auth
ADD COLUMN is_verified BOOLEAN DEFAULT FALSE;

ALTER TABLE auth
ADD COLUMN is_active BOOLEAN DEFAULT FALSE;