
ALTER TABLE sender
ALTER COLUMN first_name DROP NOT NULL;



ALTER TABLE sender
ALTER COLUMN last_name DROP NOT NULL;


ALTER TABLE sender
ADD COLUMN is_verified BOOLEAN DEFAULT FALSE;



ALTER TABLE sender
ADD COLUMN is_active BOOLEAN DEFAULT FALSE;
