name: logi CI

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout action
              uses: actions/checkout@v4

            - name: setup golang
              uses: actions/setup-go@v5
              with:
                go-version: '1.24.4'
            
            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                path: |
                    ~/.cache/go-build
                    ~/.go/pkg/mod
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                    ${{ runner.os }}-go-
            
            - name: Install dependencies
              run: go mod download
            
            - name: Run tests
              run: go test ./...
            
            - name: Check formatting
              run: |
                if [ "$(gofmt -l . | wc -l)" -gt 0]; then
                    echo "Code is not formatted. Run 'gofmt -w .'"
                    exit 1
                fi
            - name: Install golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                version: latest
            
            - name: Run linter
              run: golangci-lint run ./...
            